version: 2
updates:
  - package-ecosystem: "bundler"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    versioning-strategy: "increase-if-necessary"
    directory: "/"
    schedule:
      interval: "daily"
