---
linters:
  SelfClosingTag:
    enabled: false
  SpaceInHtmlTag:
    enabled: false # TODO
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Metrics/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Style/StringLiterals:
        Exclude: # TODO
          - app/views/browse/*
          - app/views/changesets/*
          - app/views/changeset_comments/*
          - app/views/diary_entries/*
          - app/views/geocoder/*
          - app/views/issues/*
          - app/views/layouts/*
          - app/views/messages/*
          - app/views/notes/*
          - app/views/notifier/*
          - app/views/oauth/*
          - app/views/oauth_clients/*
          - app/views/redactions/*
          - app/views/reports/*
          - app/views/site/*
          - app/views/traces/*
          - app/views/user_blocks/*
          - app/views/users/*
      Rails/DynamicFindBy:
        Enabled: false # TODO
      Style/AndOr:
        Enabled: false # TODO
      Style/WordArray:
        Enabled: false # TODO
      Style/MethodCallWithoutArgsParentheses:
        Enabled: false # TODO
      Layout/LeadingBlankLines:
        Enabled: false # TODO
      Style/NestedParenthesizedCalls:
        Enabled: false # TODO
      Rails/LinkToBlank:
        Enabled: false # TODO
      Style/SymbolProc:
        Enabled: false # TODO
      Style/Not:
        Enabled: false # TODO
      Style/NegatedIf:
        Enabled: false # TODO
      Style/ConditionalAssignment:
        Enabled: false # TODO
exclude:
  - '**/vendor/**'
