---
linters:
  SelfClosingTag:
    enabled: false
  SpaceInHtmlTag:
    enabled: false # TODO
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingBlankLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false
      Metrics/LineLength:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
      Rails/OutputSafety:
        Enabled: false
      Rails/DynamicFindBy:
        Enabled: false # TODO
      Style/WordArray:
        Enabled: false # TODO
      Layout/LeadingBlankLines:
        Enabled: false # TODO
      Style/NestedParenthesizedCalls:
        Enabled: false # TODO
      Rails/LinkToBlank:
        Enabled: false # TODO
      Style/ConditionalAssignment:
        Enabled: false # TODO
exclude:
  - '**/vendor/**'
