inherit_from: .rubocop_todo.yml

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5

Rails:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: true

Lint/PercentStringArray:
  Exclude:
    - 'config/initializers/secure_headers.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/site_controller.rb'

Naming/FileName:
  Exclude:
    - 'script/deliver-message'
    - 'script/locale/reload-languages'
    - 'script/update-spam-blocks'

Naming/UncommunicativeMethodParamName:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*.rb'
    - 'app/controllers/users_controller.rb'

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FormatStringToken:
  EnforcedStyle: template

Style/IfInsideElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - 'lib/tasks/testing.rake'
    - 'config/initializers/wrap_parameters.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets
