inherit_from: .rubocop_todo.yml

AllCops:
   RunRailsCops: true

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FileName:
  Exclude:
    - 'script/deliver-message'
    - 'script/locale/reload-languages'
    - 'script/update-spam-blocks'

Style/GlobalVars:
  Exclude:
    - 'lib/quad_tile/extconf.rb'
    
Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - 'lib/tasks/testing.rake'
    - 'config/initializers/wrap_parameters.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
