inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*.builder'

Rails:
  Enabled: true

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ExtraSpacing:
  AllowForAlignment: true

Style/FileName:
  Exclude:
    - 'script/deliver-message'
    - 'script/locale/reload-languages'
    - 'script/update-spam-blocks'

Style/IfInsideElse:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'lib/quad_tile/extconf.rb'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Exclude:
    - 'lib/tasks/testing.rake'
    - 'config/initializers/wrap_parameters.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/*.rb'
    - 'app/controllers/user_controller.rb'
