version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      # don't mount tmp directory (https://github.com/Shopify/bootsnap/issues/177)
      - /app/tmp
    ports:
      - "3000:3000"
    environment:
      # https://github.com/Shopify/bootsnap/issues/262
      ENABLE_BOOTSNAP: 'false'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    ports:
      - "54321:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: openstreetmap
    volumes:
      - ./docker-db-data:/var/lib/postgresql/data
