sotmasia2017:
  id: sotmasia2017
  alt: State of the Map Asia 2017
  link: http://stateofthemap.asia/
  img: banners/sotmasia-2017-banner.png
  enddate: 2017-sep-25
sotmus2017:
  id: sotmus2017
  alt: State of the Map US 2017
  link: https://2017.stateofthemap.us/
  img: banners/banner-sotmus2017.png
  enddate: 2017-oct-20
