sotmasia2016:
  id: sotmasia2016
  alt: State of the Map Asia 2016
  link: http://stateofthemap.asia/
  img: banners/sotmasia-2016.jpg
  enddate: 2016-oct-01

donate2016:
  id: donate2016
  alt: OpenStreetMap Funding Drive 2016
  link: https://donate.openstreetmap.org/
  img: banners/donate-2016.jpg
  enddate: 2016-oct-31

sotmlatam2016:
  id: sotmlatam2016
  alt: State of the Map Latam 2016
  link: http://state.osmlatam.org/
  img: banners/sotmlatam-2016.jpg
  enddate: 2016-nov-25
