sotmus2016:
  id: sotmus2016
  alt: State of the Map US 2016
  link: http://stateofthemap.us/
  img: banners/sotmus-2016.jpg
  enddate: 2016-jul-23

sotm2016:
  id: sotm2016
  alt: State of the Map 2016
  link: http://2016.stateofthemap.org/
  img: banners/sotm-2016.jpg
  enddate: 2016-sep-23
