sotm2018:
  id: sotm2018
  alt: SotM 2018
  link: https://2018.stateofthemap.org/
  img: banners/sotm2018.png
  enddate: 2018-jul-30
saveyourinternet:
  id: saveyourinternet
  alt: "The EU Copyright Directive threatens free content on the Internet and OpenStreetMap. Demonstrations in various European cities on 23 March. https://savetheinternet.info/demos"
  link: https://savetheinternet.info/demos
  img: banners/saveyourinternet.png
  enddate: 2019-mar-26
