sotm_2020:
  id: osm16birthday
  alt: OpenStreetMap 16th Birthday
  link: https://blog.openstreetmap.org/2020/08/01/celebrate-the-16th-osm-anniversary/
  img: banners/osm_16_birthday.png
  enddate: 2020-aug-15
