defaults: &defaults
  # Application status - possible values are:
  #   :online - online and operating normally
  #   :api_readonly - site online but API in read-only mode
  #   :api_offline - site online but API offline
  #   :database_readonly - database and site in read-only mode
  #   :database_offline - database offline with site in emergency mode
  #   :gpx_offline - gpx storage offline
  status: :online

development:
  <<: *defaults

production:
  <<: *defaults

test:
  <<: *defaults
