files:
  - "**/*.js"
exclude_paths:
  - "vendor/assets/javascripts"
options:
  eqeqeq: true
  freeze: true
  latedef: "nofunc"
  noarg: true
  noempty: true
  nonew: true
  undef: true
  browser: true
  jquery: true
  unused: true
  trailing: true
  globals:
    I18n: true
    L: true
    OSM: true
    Piwik: true
    escapeHTML: false
    getUserIcon: false
    initializeBrowse: false
    initializeNotes: false
    maximiseMap: false
    minimiseMap: false
    querystring: false
    remoteEditHandler: false
    updateLinks: false
