# Trace directories for testing
gpx_trace_dir: <%= Rails.root.join("test", "gpx", "traces") %>
gpx_image_dir: <%= Rails.root.join("test", "gpx", "images") %>
# Geonames credentials for testing
geonames_username: "dummy"
# External authentication credentials for testing
google_auth_id: "dummy"
google_auth_secret: "dummy"
google_openid_realm: "https://www.openstreetmap.org"
facebook_auth_id: "dummy"
facebook_auth_secret: "dummy"
windowslive_auth_id: "dummy"
windowslive_auth_secret: "dummy"
github_auth_id: "dummy"
github_auth_secret: "dummy"
wikipedia_auth_id: "dummy"
wikipedia_auth_secret: "dummy"
